// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace RequestsForRights.Database.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddAclUsersCorrection : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAclUsersCorrection));
        
        string IMigrationMetadata.Id
        {
            get { return "201612280414019_AddAclUsersCorrection"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
