// <auto-generated />
namespace RequestsForRights.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddAgreements : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAgreements));
        
        string IMigrationMetadata.Id
        {
            get { return "201612280321163_AddAgreements"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
