// <auto-generated />
namespace RequestsForRights.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IX_IdResourceRight_IdRequestRightGrantType_Deleted : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IX_IdResourceRight_IdRequestRightGrantType_Deleted));
        
        string IMigrationMetadata.Id
        {
            get { return "201701260628011_IX_IdResourceRight_IdRequestRightGrantType_Deleted"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
